name: Auto Assign and request review
on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]

jobs:
  assign:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const allPossibleReviewers = ['zagorky', 'anastanei', 'savryna', 'JsPowWow']; 
            const reviewers = allPossibleReviewers.filter(reviewer => reviewer !== author);

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.pull_request.user.login]
            })
            
            if (!context.payload.pull_request.draft) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: reviewers
              });
            }

