name: SecondChapter-Node.js CI

on:
  push:
    branches: [ "develop", "main", "release/sprint-*" ]
  pull_request:
    branches: [ "develop", "main", "release/sprint-*" ]
jobs:
  test-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run type-check --if-present
      - run: npm run lint
      - run: npm run format --if-present
      - run: npm test --if-present